service: drebedengi-slack

frameworkVersion: "3"
useDotenv: true

plugins:
  - serverless-plugin-typescript
  - serverless-offline

provider:
  name: aws
  runtime: nodejs14.x

functions:
  hello:
    handler: handler.hello
    events:
      - http: get /hello
  slack:
    handler: src/main.handler
    events:
      - http:
          path: slack/events
          method: post
